services:
  backend:
    build: .
    ports: 
      - ${BACKEND_PORT}:4000
    environment:
      - PHX_SERVER=true
      - PHX_HOST=${PHX_HOST}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - PHX_SCHEME=${PHX_SCHEME}
      - PHX_PORT=${PHX_PORT}